export const theme = {
  colors: {
    cardColor: '#471CA9',
    black: '#000',
    white: '#fff',
    text: '#2a2a2a',
    background: '#e7e7e7',
    primary: '#07c',
    secondary: 'red',
    accent: '#0c7ee1d7',
    muted: '#f6f6f6',
    border: '#bdb9b9',
    backgroundFirst: '#0c7ee1',
    backgroundSecond: '#b449ba',
    backgroundThird: '#ff0000',
    backgroundFourth: '#008080',
    chipColorOnline: 'green',
    chipColorOfline: 'red',
    tableHeadBackground: '#83d4f2',
    tableBackgroundSecond: '#6a68681e',
    tableBackgroundFirst: '#fff',
    tableBorder: '#aeaaaa3d',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '32px',
    xl: '64px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    round: '50%',
  },
};
